spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: db_user
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 8081
  servlet:
    context-path: /api
